-- Public chat sessions for the embeddable Aliice chat widget
-- These are conversations with website visitors (not internal staff chats)

create table if not exists public_chat_sessions (
  id uuid primary key default gen_random_uuid(),
  
  -- Visitor identification
  visitor_id text, -- anonymous visitor ID from cookie/localStorage
  visitor_name text,
  visitor_email text,
  visitor_phone text,
  
  -- Session metadata
  status text not null default 'active' check (status in ('active', 'closed', 'converted')),
  conversation_type text default 'general' check (conversation_type in ('general', 'booking', 'inquiry', 'support', 'consultation')),
  
  -- Attribution tracking
  source_url text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  
  -- Location/service interest extracted from conversation
  interested_service text,
  interested_location text,
  
  -- Patient connection
  patient_id uuid references patients(id) on delete set null,
  patient_match_type text check (patient_match_type in ('email', 'phone', 'manual', 'created')),
  
  -- AI extracted data (JSON for flexibility)
  extracted_data jsonb default '{}'::jsonb,
  
  -- Summary generated by AI
  conversation_summary text,
  
  -- Timestamps
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  closed_at timestamptz,
  
  -- Message count cache for quick display
  message_count integer default 0
);

-- Indexes for common queries
create index if not exists public_chat_sessions_visitor_email_idx on public_chat_sessions(visitor_email);
create index if not exists public_chat_sessions_visitor_phone_idx on public_chat_sessions(visitor_phone);
create index if not exists public_chat_sessions_patient_id_idx on public_chat_sessions(patient_id);
create index if not exists public_chat_sessions_status_idx on public_chat_sessions(status);
create index if not exists public_chat_sessions_created_at_idx on public_chat_sessions(created_at desc);
create index if not exists public_chat_sessions_conversation_type_idx on public_chat_sessions(conversation_type);

-- Public chat messages
create table if not exists public_chat_messages (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public_chat_sessions(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamptz default now()
);

create index if not exists public_chat_messages_session_id_idx on public_chat_messages(session_id);
create index if not exists public_chat_messages_created_at_idx on public_chat_messages(session_id, created_at);

-- Trigger to update message count and updated_at
create or replace function update_public_chat_session_on_message()
returns trigger as $$
begin
  update public_chat_sessions
  set 
    message_count = (select count(*) from public_chat_messages where session_id = NEW.session_id),
    updated_at = now()
  where id = NEW.session_id;
  return NEW;
end;
$$ language plpgsql;

drop trigger if exists public_chat_message_count_trigger on public_chat_messages;
create trigger public_chat_message_count_trigger
  after insert on public_chat_messages
  for each row
  execute function update_public_chat_session_on_message();

-- RLS policies for public chat (allow public insert, admin read)
alter table public_chat_sessions enable row level security;
alter table public_chat_messages enable row level security;

-- Allow anyone to insert new sessions (public widget)
create policy "Anyone can create public chat sessions"
  on public_chat_sessions for insert
  with check (true);

-- Allow anyone to update their own session (by visitor_id)
create policy "Anyone can update their own public chat session"
  on public_chat_sessions for update
  using (true);

-- Allow authenticated users to read all sessions
create policy "Authenticated users can read public chat sessions"
  on public_chat_sessions for select
  to authenticated
  using (true);

-- Allow anyone to insert messages
create policy "Anyone can insert public chat messages"
  on public_chat_messages for insert
  with check (true);

-- Allow authenticated users to read all messages
create policy "Authenticated users can read public chat messages"
  on public_chat_messages for select
  to authenticated
  using (true);
