-- Recurrence identity is separate from appointment_group_id, which groups
-- simultaneous provider reservations.
ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS recurrence_series_id uuid,
  ADD COLUMN IF NOT EXISTS recurrence_sequence integer;

CREATE INDEX IF NOT EXISTS appointments_recurrence_series_start_idx
  ON appointments (recurrence_series_id, start_time)
  WHERE recurrence_series_id IS NOT NULL;

COMMENT ON COLUMN appointments.recurrence_series_id IS
  'Shared identifier for occurrences generated by one recurring appointment rule.';
COMMENT ON COLUMN appointments.recurrence_sequence IS
  'Zero-based position of an occurrence within its recurring series.';
